Dev2
Stint19/FinalTask pull request #1
Opened 2022-12-06 08:13 UTC by Stint19

2022-12-07 22:03 UTC, Sputnavi requested changes

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/appsettings.json
> +    "ConnStr": "Data Source=.;Initial Catalog=FinalTask;Integrated Security=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;Encrypt = false"
В appsettings.json хранятся только общие настройки, которые почти никогда не меняются, например: конфигурация логгера, время жизни токена и тд.
Все коннекшн стринги, урлы на сторонние апишки для локальной разработки хранятся в appsettings.Development.json или для рабочего приложения на каком-нибудь хостинг сервере используется appsettings.{Environment}.json
Одним из явных признаков неправильности настройки в appsetings.json является содержание localhost в любой из настроек

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/appsettings.json
> +    "ConnStr": "Data Source=.;Initial Catalog=FinalTask;Integrated Security=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;Encrypt = false"
Никогда не сокращаем название переменных или настроек, потому что есть множество вариаций написания в сокращенном виде: ConStr, ConString, ConnecString - все это путает интуитивное написание кода и его читаемость

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/Services/Domain/TokenService.cs
> +                throw new SecurityTokenException("Invalid token");
Даже если после if у нас одна строчка кода, ее лучше оборачивать в скобки { }, есть такое соглашение среди разработчиков. В случае если захочется добавить еще одну строку кода в логику, можно не заметить не захождение в условие и получить баг

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/Services/Domain/TokenService.cs
> +            _ = int.TryParse(_configuration["JWT:TokenValidityInMinutes"], out int tokenValidityInMinutes);
А что будет, если TokenValidityInMinutes="SomeText"? В таком случае мы теряем ошибку, мы получим validity = 0 и токен не будет работать совсем. Если что-то не так в конфигах - бросаем ошибку

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/Repositories/Interfaces/IProductRepository.cs
> +        List<Product> Get();
Почему синхронно?

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/Repositories/Interfaces/IProductRepository.cs
> +        Product Post(Product product);
Методы репозитория должны явно описывать свои действия, POST - это HTTP метод. Нужно называть методы с их намерениями, в данном случае это Create. Если мы решим написать desktop приложение и использовать этот репозиторий, то Post вообще не имеет смысла для разработчиков, не знающих web / rest

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/Program.cs
> +public partial class Program { }
Зачем это нужно?

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/Program.cs
> +// Authentication & Authorization
Тут действительно нужен этот комментарий? Комментарии стараются не оставлять, код должен быть самодокументирующимся с помощью правильных названий переменных, методов, классов. Комментарии оставляются лишь в том случае, если было принято не очень очевидное решение и нужно пояснить его.
В данном случае и так понятно что здесь

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/Middlewares/LogUrlMiddleware.cs
> +            throw new ArgumentNullException(nameof(loggerFactory));
Нужно следить за форматированием, добавить таб перед throw или оставить все в одной строке

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/Middlewares/LogUrlMiddleware.cs
> +            _logger.LogInformation($"Request URL: {Microsoft.AspNetCore.Http.Extensions.UriHelper.GetDisplayUrl(context.Request)}");
Слишком длинно, хотя есть возможность использовать using

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/Middlewares/LogURLMiddlewareExtensions.cs
> +    public static class LogURLMiddlewareExtensions
Все-таки это не LogURLMiddlewareExtensions, а ApplicationBuilderExtensions. Должно находится в другой папке - Extensions, которая обычно используется и для других Extension методов

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/Controllers/ProductController.cs
> +        // GET: api/<ProductController>
Много отступов, комментарий лишний - мы и так знаем route, глядя на код

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/Controllers/ProductController.cs
> +            _productRepository = productRepository;
Здесь должен быть сервис, тут репозитория быть не должно - он должен быть в сервисе. Стараемся соблюдать архитектуру - приложение должно быть готово к расширению логики.

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/Controllers/ProductController.cs
> +                return StatusCode(200, result);
Нужно стараться использовать OK, Created и тд, чистый StatusCode не лучшая практика

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/Controllers/ProductController.cs
> +                throw;
Никогда не дойдем до этого throw и в целом не должны делать его.
А если мы просто не найдем продукт по Id должен быть NotFound.

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/Controllers/AuthenticateController.cs
> +                user.RefreshTokenExpiryTime = DateTime.Now.AddDays(refreshTokenValidityInDays);
Такая логика должна выносится в сервис, а не в контроллер

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/Controllers/AuthenticateController.cs
> +            if (user != null && await _userManager.CheckPasswordAsync(user, model.Password))
Этот иф нужно инвертировать: поменять так, чтобы в плохих сценариях сразу выходить из метода, а не делать всю логику во вложенном ифе

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/Controllers/AuthenticateController.cs
> +                return StatusCode(StatusCodes.Status500InternalServerError, new Response { Status = "Error", Message = "User already exists!" });
500 - это неожиданная ошибка на сервере. В данном случае больше подойдет знаменитый 400 BadRequest или 409 Conflict. Нужно избегать использование StatusCode

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/Controllers/AuthenticateController.cs
> +                return StatusCode(StatusCodes.Status500InternalServerError, new Response { Status = "Error", Message = "User creation failed! Please check user details and try again." });
500 не подойдет

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/Controllers/AuthenticateController.cs
> +                await _roleManager.CreateAsync(new IdentityRole(UserRoles.Admin));
Так делать не стоит, должно находится в другом месте и проверять / выполнять только один раз. Поищи как правильно сделать seed roles

2022-12-07 22:03 UTC, Sputnavi commented on JWTRefreshToken.NET6.0/Controllers/AuthenticateController.cs
> +            if (user == null) return BadRequest("Invalid user name");
Выражения не пишут в одну строку - очень тяжело дебажить

2022-12-07 22:03 UTC, Sputnavi commented on FinalTask.IntegrationTests/ProductsControllerTests.cs
> +        public async Task Get_ProductById_ShouldReturnUnauthorized()
Одного IntegrationTest мало, покрой всей эндпоинты ProductConrtoller

2022-12-07 22:03 UTC, Sputnavi commented on FinalTask.IntegrationTests/ProductsControllerTests.cs
> +                    var mockService = new Mock<IProductRepository>();
В интегрейшн тестах не делают моки

2022-12-07 22:03 UTC, Sputnavi commented on FinalTask.IntegrationTests/ProductsControllerTests.cs
> +            WebApplicationFactory<Program> webHost = new WebApplicationFactory<Program>().WithWebHostBuilder(builder =>
Не инициализируют webHost для каждого теста - это очень затратно. Его делают один раз для всех интегрейшн тестов одного класса, то есть 1 webHost на весь ProductController IntegrationTests

2022-12-07 22:03 UTC, Sputnavi commented on ApiUnitTests/FinalTask.UnitTests.csproj
> +    <PackageReference Include="MSTest.TestAdapter" Version="2.2.8" />
MSTest встречается довольно редко, xUnit самый популярный. Просто для твоей информации, переделывать не надо

2022-12-07 22:03 UTC, Sputnavi commented on ApiUnitTests/ProductControllerTests.cs
> +            Assert.AreEqual(200, obj.StatusCode);
Мало проверить статус код, нужно еще проверить контент ответа: количество продуктов, проверить все поля каждого продукта

2022-12-07 22:03 UTC, Sputnavi commented on ApiUnitTests/ProductControllerTests.cs
> +            Assert.AreEqual(400, obj.StatusCode);
Нужно проверить контент, сообщение в нем

2022-12-07 22:03 UTC, Sputnavi commented on ApiUnitTests/ProductControllerTests.cs
> +
Нужно покрывать классы тестами полностью: все методы, положительные и отрицательные случаи. Также тут не хватает теста для GetById

2022-12-07 22:03 UTC, Sputnavi commented on ApiUnitTests/ProductRepositoryTests.cs
> +    {
В этих тестах учесть замечания для тестов контроллера

2022-12-07 22:11 UTC, Sputnavi commented
Продолжай делать правки в этой ветке. Мержить и завершать ПР нельзя.

2022-12-13 11:53 UTC, Stint19 commented
Сделал правки, можно ревьювить. Проекты новые сделал, так как переносил все на чистую архитектуру @Sputnavi

2022-12-20 21:59 UTC, Sputnavi requested changes

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.Application/Dtos/LoginModel.cs
> +namespace FinalTask.Application.Dtos
Молодец, что переделал имена нэймспейсов на нормальные

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.Application/Exceprions/InvalidConfigExceprion.cs
> +        public InvalidConfigExceprion() : base("Invalid configuration")
Нужно стараться писать полностью слова в названиях, то есть здесь лучше написать InvalidConfigurationException. И еще нужно стараться проверять классы на опечатки: Excep**t**ion. Обычно IDE либо их расширения предлагают встроенные спелл чеки

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.Application/Exceprions/ModelNotFoundException.cs
> +    public class ModelNotFoundException : Exception
Модель - это класс, вряд ли мы ищем классы в нашем приложении, тут больше подходит Entity

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.Application/Exceprions/ModelNotFoundException.cs
> +            : base("Entity was not found!")
Эксепшн, который скрывает детали. Эксепшн должен содержать максимальное количество деталей, по которым можно понять и найти ошибку, в данном случае поискать энтити с нужной айди

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.Application/Services/ProductService.cs
> +            await CheckIfExistsAsync(product);
Больно знакомый и плохой код...
Валидация делается отдельно для каждого метода, хоть порой это и дублирование кода, поэтому метод не нужен, да и нейминг плохой

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.Application/Services/ProductService.cs
> +            await CheckIfFound(id, item);
Для этого метода то же самое

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.Application/Services/ProductService.cs
> +            item.Price = product.Price;
Не хватает автомаппера и разделения логических частей пустыми строками

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.Domain/Properties/launchSettings.json
> +  "profiles": {
Нам не нужны лаунч сеттинги для библиотечных проектов

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.Infrastucture/Repositories/ProductRepository.cs
> +            await _appDbContext.SaveChangesAsync();
Проблемка, теряем гибкость и перфоманс, отказываясь от транзакций. Нужно использовать только очень осознанно, но даже так это не лучший вариант. Поэтому возвращаемся к классическому варианту, когда у репозитория есть метод сэйв ченжес

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.IntegrationTest/ProductControllerTests.cs
> +            var products = DbOption.GetSeedUsers().ToList();
Какое-то лишнее действие

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.IntegrationTest/ProductControllerTests.cs
> +            var response = await _client.GetAsync("api/Product");
Это не эррэнж, здесь ты должен был сделать тестовый продукт для гета любым способом: заново инициализировать бд или создать продукт через пост

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.IntegrationTest/ProductControllerTests.cs
> +        public async Task GetProduct_ShouldReturnOk_WithValidId()
Нейминг тестов обычно такой: ИмяМетода_Условие_Результат

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.IntegrationTest/ProductControllerTests.cs
> +            using (new AssertionScope())
Ассершн скоуп на практике используют редко, за весь коммерческий опыт ни разу не встретил. Тем более используешь FluentAssertion, который позволяет быстро проверять через BeEquivalentTo(), который полезен при наличии объекта на руках и можно гибко настроить

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.IntegrationTest/ProductControllerTests.cs
> +            product.Should().BeEquivalentTo(new ProductModel
Не рекомендовал бы так делать, когда нет объекта на руках, к тому же тесты часто похожи друг на друга и копируются. Лучше проверять построчно каждое поле отдельно, но только если нет готового объекта того же типа

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.UnitTests/ProductControllerTests.cs
> +            var productService = new Mock<IProductService>();
Моки выносятся в поля и инициализируются в конструкторе, так мы освобождаем наши тесты от лишнего кода инициализации, который все равно будет нужен, в самих тестах будут только сетапы моков

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.UnitTests/ProductControllerTests.cs
> +                .Returns(Task.FromResult(GetFakeProducts()));
Есть ReturnsAsync, который освободит нас от Task.FromResult

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.UnitTests/ProductControllerTests.cs
> +            productService.Setup(c => c.UpdateProductAsync(It.IsAny<int>(), It.IsAny<ProductModel>()));
В сетапах указывают точные параметры и стараются избегать It класс в целом, он нужен только в крайне тяжелых тестах, здесь нужно хотя бы указазать правильный айдишник

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.UnitTests/ProductControllerTests.cs
> +                r.UpdateProductAsync(It.IsAny<int>(), It.IsAny<ProductModel>()));
А на верифае проверять с нужными параметрами, здесь хотя бы с айдишником

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.UnitTests/ProductServiceTests.cs
> +            Assert.Equal(productList.Count, result.Count);
Слабая проверка, нужно еще проверить содержимое коллекции

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.UnitTests/ProductServiceTests.cs
> +        {
Тест ни о чем. Еще метод не должен отправлять спутник в космос, почему не проверил? :D

Тесты должны покрыть каждую строчку кода: войти во все ифы и их элсы, зайти в ифы по всем возможным условиям, если есть &&,||;
То есть должны покрыть все положительные и отрицательные кейсы, где положительный - успешный результат, а отрицательный - любой результат из else, например BadRequest, NotFound, пустой объект или эксепшн. Лишнего придумывать не надо и предполагать какие-то события тоже, просто нужно идти построчно по тестируемому методу.

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.UnitTests/ProductServiceTests.cs
> +            Assert.Throws<MockException>(() => productRepository.Verify());
Непонятно, что тут проверяется. Есть более подходящие проверки в моке, например чек вызвалось 0 раз - Times.Never

2022-12-20 21:59 UTC, Sputnavi commented on FinalTask.WebApi/Extensions/JwtExtensions.cs
> +                    Description = "JWT Authorization header using the Bearer scheme. \r\n\r\n Enter 'Bearer' [space] and then your token in the text input below.\r\n\r\nExample: \"Bearer 1safsfsdfdfd
По прежнему плохой пример токена

2022-12-27 18:46 UTC, Stint19 commented
Сделал правки, можно ревьювить @Sputnavi

2023-01-04 21:10 UTC, Sputnavi requested changes
В целом могу похвалить, есть прогресс и было приятнее проверять :)
Делай правки и пингуй на ревью

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.Application/Exceptions/InvalidConfigurationExceprion.cs
> +    {
В названии файла по прежнему опечатка

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.Application/Mapper/MapProfiles.cs
> +                opt => opt.Ignore());
Не очень удачное форматирование, лучше оставить на делегат на той же строке, то есть 13 строчка должна быть в 12

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.Application/Services/ProductService.cs
> +                throw new ArgumentException("This product already exist.");
В сообщении эксепшна не хватает уточнения про какой продукт идет речь. Представь, что ты шлешь много запросов из какого-то приложения в эту АПИ и в логах приложения видишь, что какой-то запрос не прошел успешно: будет очень тяжело найти ошибку, поэтому не хватает деталей.

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.Application/Services/ProductService.cs
> +                throw new ArgumentException("This product already exist.");
Еще ты начал использовать подход с глобал эксепшн хэндлером, в котором есть часть бизнес логики - должен придерживаться до конца такого подхода и сделать отдельный эксепшн на случай, если энтити уже существует. Особенно хорошо это обосновывается выбором статус кода на этот случай: если энтити уже существует, то используют 409 Conflict статус код

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.Application/Services/AuthService.cs
>              if (user == null)
Здесь проверка на `null` через `==`

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.Application/Services/ProductService.cs
> +            if (item is null)
А здесь проверка через `is null`. Оба варианта правильные, но не надо смешивать подходы и нужно по возможности оставлять консистентность кода. Тут дело вкуса, выбирай любой. Проверка на неравенство `null` через `is` можно делать через `is not null` - подходы полностью взаимозаменяемые

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.Infrastucture/Repositories/ProductRepository.cs
>              await _appDbContext.SaveChangesAsync();
Почему здесь осталось `SaveChangesAsync`? Если мы захотим создать в цикле много записей, получим N запросов вместо 1

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.UnitTests/ProductControllerTests.cs
> +        public async Task GetProduct_WithNotValidId_ShouldReturnModelNotFoundException()
Контроллер у нас не возвращает модель эксепшна, он бросает эксепшн, то есть как результат в названии теста должно быть что-то вроде `ThrowsNotFoundException`

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.UnitTests/ProductControllerTests.cs
>                  .Returns(Task.FromResult(new ProductModel
ReturnsAsync

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.UnitTests/ProductControllerTests.cs
> +            _productService.Setup(c => c.UpdateProductAsync(1, product));
Здесь сделан сетап на переменную `product` для метода `UpdateProductAsync`, она проверяется по ссылке и такое сравнение чаще всего не подойдет. Может быть такая ситуация, что в этот метод не будет напрямую передаваться модель из контроллера, а например новая модель на основе `product`. В таком случае нам надо будет все равно убедиться, что новая модель использует нужные данные и передается в `UpdateProductAsync`.
Для этого в MOQ есть класс It, который умеет примерно вот так `It.Is<ProductModel>((pm) => pm.Name == "Test123");`. Обычно сложные проверки делаются таким образом, к тому же спасают от проверок по ссылке. Примерно так же делается и в `Verify`.

И это только в случае ссылочных типов, значимые проверяются легко - айдишку засетапил и проверяешь правильно.

Стараются избегать It.IsAny и It.IsAnyType, т.к. плохо тестируют на параметры, но It.Is с колбэком является хорошей практикой

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.UnitTests/ProductControllerTests.cs
> +            _productService.Setup(r => r.DeleteProductAsync(It.IsAny<int>()));
Здесь легко можно проверить на параметр

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.UnitTests/ProductServiceTests.cs
>                      .Returns(Task.FromResult(new Product() {
ReturnsAsync поправь везде

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.UnitTests/ProductServiceTests.cs
>                  .Verifiable();
Кажется `.Verifiable()` лишнее

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.WebApi/Controllers/ProductController.cs
> +       // [Authorize(Roles = "User")]
Уже не нужна авторизация?

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.WebApi/Extensions/JwtExtensions.cs
> +                    Description = "JWT Authorization header using the Bearer scheme. \r\n\r\n Enter 'Bearer' [space] " +
Кстати, это же по сути не JWT extensions, а просто ServiceCollectionExtensions.
Как правильно понимать куда запихнуть экстеншн методы: 
1) Смотрим какого типа параметр после this, видим `SomeType`
2) К этому типу добавляем слово **Extensions**
3) Найти файл / класс с таким названием и добавить туда этот метод. Если файла / класса нет, смотреть пункт 4
4) Создать файл / класс `SomeTypeExtensions` в папке Extensions и добавить туда метод

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.Application/FinalTask.Application.csproj
> +    <ProjectReference Include="..\FinalTask.Domain\FinalTask.Domain.csproj" />
В Application.csproj не надо ссылаться на Domain, т.к. уже добавлен Infrastucture, в котором уже есть Domain. Лишняя ссылка, которая замедляет билд проекта

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.WebApi/FinalTask.WebApi.csproj
> +    <ProjectReference Include="..\FinalTask.Infrastucture\FinalTask.Infrastucture.csproj" />
Здесь по такой же логике Domain и Infrastucture лишние, т.к. они идут из Application

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.UnitTests/FinalTask.UnitTests.csproj
> +    <ProjectReference Include="..\FinalTask.Application\FinalTask.Application.csproj" />
Такая же логика с ссылками

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.IntegrationTest/FinalTask.IntegrationTest.csproj
> +    <ProjectReference Include="..\FinalTask.Infrastucture\FinalTask.Infrastucture.csproj" />
Такая же логика с ссылками

2023-01-04 21:10 UTC, Sputnavi commented on FinalTask.IntegrationTest/FinalTask.IntegrationTest.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.0" />
И тоже лишний пакет, который в итоге идет из Infrastucture

2023-01-06 16:11 UTC, Stint19 commented on FinalTask.Infrastucture/Repositories/ProductRepository.cs
>              await _appDbContext.SaveChangesAsync();
EF автоматически генерит id для каждого объекта после SaveChangesAsync. Возможно нужно было изначально использовать Guid и герерировать вручную его. Но пока не понятно как получить сгенерированную id без SaveChangesAsync

2023-01-06 16:12 UTC, Stint19 commented on FinalTask.Infrastucture/Repositories/ProductRepository.cs
>              await _appDbContext.SaveChangesAsync();
@Sputnavi . Не знаю, надо пинговать тут или нет, на всякий напишу

2023-01-06 17:28 UTC, Stint19 commented on FinalTask.Infrastucture/Repositories/ProductRepository.cs
>              await _appDbContext.SaveChangesAsync();
Всё. Разобрался

2023-01-06 17:39 UTC, Stint19 commented
Сделал правки, можно ревьювить @Sputnavi

2023-01-17 21:21 UTC, Sputnavi commented
Выглядит хорошо, замечаний нет, проверка окончена

2023-01-19 10:10 UTC, merged